name = "terminimal"
description = "A simple, minimal retro theme"
license = "MIT"
homepage = "https://github.com/pawroman/zola-theme-terminimal"
min_version = "0.11.0"

# An optional live demo URL
#demo = "https://pawroman.github.io/zola-theme-terminimal/"

[author]
name = "Dichgrem"
homepage = "https://github.com/Dichgrem"

# The original theme this one's been forked off.
[original]
author =  "Dichgrem"
homepage = "https://github.com/Dichgrem"
#repo = "https://github.com/panr/hugo-theme-terminal"

[extra]
# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "Dichgrem"

# One of: blue, green, orange, pink, red.
# Defaults to blue.
# Append -light for light themes, e.g. blue-light
# Or append -auto, e.g. blue-auto
accent_color = "blue"

# One of: blue, dark, green, orange, pink, red, light, auto
# Enabling dark background will also modify primary font color to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "dark"

# The logo text - defaults to 2 non-breaking spaces.
logo_text = "Terminimal theme"

# Whether to show links to earlier and later posts
# on each post page.
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = false
